service: blinkist-project-3
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1

functions:
  hello:
    handler: handler.handle	
    environment: 
      appid: ${ssm:/appid~true}

